AWSTemplateFormatVersion: 2010-09-09
Description: samuel kawuldim / Compudemy - This template deploys a VPC
Resources:
VPC:
 Type: 'AWS::EC2::VPC'
 Properties:
   CidrBlock: 10.0.0.0/16
   EnableDnsHostnames: 'true'
